### PR TITLE
Adding tasks to automate building GitHub pages from strings docs

### PR DESCRIPTION
**Pull request by danzilio**

### CODE REVIEW

**Comment by jyaworski** [comment]
I feel the git gem would be better suited, here.

**Comment by danzilio** [comment]
I'm hesitant to add another dependency

**Comment by jyaworski** [comment]
Considering this is moving to be a gem, I feel it's OK to add another dependency.

**Comment by HAIL9000** [comment]
@danzilio Thanks for the contribution! Going to test this out soon when I get a few free minutes. 

Would using the git gem simplify this significantly? I'm also kind of hesitant to add another dependency just for a task that's not essential to the core workflow.

**Comment by HAIL9000** [comment]
Hey @danzilio, sorry for the delay, I'm just about ready to merge this. We've been documenting the Rake tasks that come with strings in the [README](https://github.com/puppetlabs/puppetlabs-strings#rake-tasks), would you have a few minutes to update the README to reflect this PR? If not, no worries at all I can merge this and then do that update myself.

**Comment by danzilio** [comment]
Yes! I can definitely do that!

**Comment by HAIL9000** [comment]
Ping @danzilio, just wanted to see if you're still interested in working on this!

**Comment by danzilio** [comment]
omg i'm so sorry @HAIL9000, this completely dropped off my radar. will have an update in just a few!

**Comment by danzilio** [comment]
@HAIL9000 added docs!

**Comment by HAIL9000** [comment]
@danzilio Thank you! Looking into why the specs are failing... I can't imagine anything in this PR would break the tests

**Comment by HAIL9000** [comment]
Okay the spec failure was due to a new YARD version (thanks @whopper!). Kicking Travis and then merging once it's green

**Pull request merged**
