### PR TITLE
Forgot defined types

### PR DESCRIPTION
**Pull request by iankronquist**
Fixes issues which Shaigy found with PDOC-19:
https://tickets.puppetlabs.com/browse/PDOC-19?focusedCommentId=199417&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-199417

### CODE REVIEW

**Comment by HAIL9000** [comment]
@iankronquist Could you just quickly add a longer description for the first commit? It makes sense now with the context, but in the future it might be a little confusing

**Comment by iankronquist** [comment]
@HAIL9000 done.

**Comment by HAIL9000** [comment]
Hmmm that PDOC-33 commit just showed up. Does this need a rebase?

**Comment by iankronquist** [comment]
@HAIL9000 there we go.

**Pull request merged**
