### PR TITLE
(PDOC-43) Advanced formatting in parameters description

### PR DESCRIPTION
**Pull request by roidelapluie**
This commit allows you to add more advanced formatting in parameters
description. This is useful to add cross-module links, or to add new
lines, emphasis and so on.

### CODE REVIEW

**Comment by iankronquist** [comment]
This needs to be rebased now that your other PR has been merged. I'm thinking that you might want to add the htmlify call to the `extract_param_details` function so it can be used by other templates which call the method, probably on lines 57 and 75.
https://github.com/puppetlabs/puppetlabs-strings/blob/master/lib/puppet_x/puppetlabs/strings/yard/templates/default/template_helper.rb#L39

**Comment by roidelapluie** [comment]
I have rebased (and even before your comment ;-) ).

Concerning where to call the function I did not succeed to call it from the other file. My ruby skills are not good enough it seems.

**Comment by iankronquist** [comment]
I like your change, but I want to be able to use it in the template for the types and providers PR coming down the pike, so it should be in the `extract_param_details` function. Here is the sort of thing I was imagining, let me know if it doesn't work.

```ruby
  def extract_param_details(parameters, tags_hash, fq_name = false)
    ...

      param_details = {:name => param_name, :desc => htmlify(description), :types => param_types, :exists? => true}
    ...

    # Check if there were any comments for parameters that do not exist
    tags_hash.each do |tag|
    ...
        parameter_info.push({:name => tag.name, :desc => htmlify(tag.text), :types => tag.types, :exists? => false})
    ...
    end
    ...
  end
```

**Comment by roidelapluie** [comment]
extract_param_details should be "output format" agnostic.

I tried several approaches  to put that into html_helper.rb but that did not work...

**Comment by iankronquist** [comment]
Interesting. I'll take a look tomorrow.

**Comment by roidelapluie** [comment]
Thanks

**Comment by iankronquist** [comment]
You need to include the HtmlHelper module before calling htmlify.

```ruby
class TemplateHelper
  include YARD::Templates::Helpers::HtmlHelper
...
def extract_param_details(parameters, tags_hash, fq_name = false)
...                                                    
    param_details = {:name => param_name, :desc => htmlify(description, :markdown), :types => param_types, :exists? => true}

...                                                         
      parameter_info.push({:name => tag.name, :desc => htmlify(tag.text, :markdown), :types => tag.types, :exists? => false})
...                                                              
end
```

**Comment by roidelapluie** [comment]
If you have to specify markdown then you break compatibility with old style config..

**Comment by iankronquist** [comment]
Good point. I specified markdown because I didn't have a reference to the Yard options object at that point in the code.

**Comment by roidelapluie** [comment]
Yes that is the problem I was facing with that approach.

**Comment by roidelapluie** [comment]
@iankronquist did you have a chance to look at this?

**Comment by iankronquist** [comment]
@roidelapluie sorry for not getting back to you. Give this a shot:
```ruby
class TemplateHelper
  include YARD::Templates::Helpers::HtmlHelper
...
def extract_param_details(parameters, tags_hash, fq_name = false, options)
...                                                    
    param_details = {:name => param_name, :desc => htmlify(description, options.markup), :types => param_types, :exists? => true}

...                                                         
      parameter_info.push({:name => tag.name, :desc => htmlify(tag.text, options.markup), :types => tag.types, :exists? => false})
...                                                              
end
```

Remember to pass options to the function everywhere it's called.
It's called in these files:
```
lib/puppet_x/puppetlabs/strings/yard/templates/default/definedtype/setup.rb
lib/puppet_x/puppetlabs/strings/yard/templates/default/definedtype/setup.rb
lib/puppet_x/puppetlabs/strings/yard/templates/default/puppetnamespace/setup.rb
lib/puppet_x/puppetlabs/strings/yard/templates/default/template_helper.rb
```

**Comment by iankronquist** [comment]
Thanks again for your help!

**Comment by iankronquist** [comment]
@roidelapluie Hey, are you still interested in fixing this up? Thanks for your help!

**Comment by HAIL9000** [comment]
Ping @roidelapluie, just checking in to see if you still want to work on this

**Comment by roidelapluie** [comment]
On Tue, Oct 06, 2015 at 03:34:33PM -0700, Hailee Kenney wrote:
> Ping @roidelapluie, just checking in to see if you still want to work on this
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/puppetlabs/puppetlabs-strings/pull/52#issuecomment-146021251


Yes I will have a look at this soon

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by HAIL9000** [comment]
@roidelapluie Awesome, thanks so much! Feel free to reach out if you have any questions

**Comment by roidelapluie** [comment]
@HAIL9000 @iankronquist done

**Comment by iankronquist** [comment]
@roidelapluie Thank you. It looks like Travis is failing right now, would you mind fixing that? I'll take a more detailed look after it passes.

**Comment by roidelapluie** [comment]
Actually can you take a look and try to see why is travis failing? I am out of ideas

**Comment by iankronquist** [comment]
It looks like it couldn't properly require the html_helper.rb file. This usually happens because of a syntax error.

**Comment by iankronquist** [comment]
Nope, I lied. Let me look into it a little more.

**Comment by iankronquist** [comment]
@roidelapluie So the first problem is that you aren't including the module the htmlify function lives in. try putting
`include YARD::Templates::Helpers::HtmlHelper` inside the TemplateHelper class. There may be other issues after that, I'm not sure. I don't have more time to investigate now, sorry.

**Comment by roidelapluie** [comment]
@iankronquist it does not make any diff

**Comment by roidelapluie** [comment]
@iankronquist  ping; do you have more ideas?

**Comment by roidelapluie** [comment]
@HAIL9000 up

**Comment by hlindberg** [comment]
Failing because of: 
```
       No such file or directory - /tmp/d20160203-20901-1i5kwpe/test/doc/test.html
     # ./spec/lib/strings_spec/module_helper.rb:18:in `read'
     # ./spec/lib/strings_spec/module_helper.rb:18:in `read_html'
     # ./spec/unit/puppet/face_spec.rb:60:in `block (5 levels) in <top (required)>'
     # ./spec/lib/strings_spec/module_helper.rb:10:in `block in using_module'
     # ./spec/lib/strings_spec/module_helper.rb:4:in `using_module'
     # ./spec/unit/puppet/face_spec.rb:55:in `block (4 levels) in <top (required)>'
```
The rest of the problems (that are not directly this) are probably caused by the same error.

**Comment by hlindberg** [comment]
@roidelapluie did you give up on this? I noticed the ticket was closed with a "won't fix".

**Comment by roidelapluie** [comment]
as I opened the ticket and decided to stop working on it, I changed it to wonfix yes

**Comment by hlindberg** [comment]
Closing this PR, but we may adopt it later if we have time.

**Comment by hlindberg** [comment]
Thanks @roidelapluie for the work you put in !

**Pull request closed without merging**
