### PR TITLE
(maint) Pin rubocop to enable spec support for ruby < 2.0

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by kylog** [comment]
Whoops rubocop doesn't pass on strings atm .... Sigh. I'll update.

**Comment by kylog** [comment]
Ping @peterhuene or @hlindberg.

**Comment by peterhuene** [comment]
We should probably drop CI for < 2.0 soon, but I'm 👍 

My work includes moving us to the latest Yard and completely overhauling puppet-strings to produce a more polished output (wrt to command line and HTML output) and fixing lots of little bugs.  Should hopefully be ready to go by early next week at the latest.

**Comment by kylog** [comment]
Maybe the polished output plus dropping old rubies would make for a 0.5.0 (or 1.0.0).

Actually we should probably ask some users of this gem about dropping the old rubies. FYI we had a similar conversation re puppet-lint in https://github.com/rodjek/puppet-lint/issues/503.

**Comment by hlindberg** [comment]
👍  asking users; no point to support older versions if there are very few or noone using strings with those.

**Pull request merged**
