### PR TITLE
(maint) Delete .rb file that was probably commited by accident

### PR DESCRIPTION
**Pull request by roidelapluie**
Extension of the file is .rb but should be .erb, so I guess thir file
was committed by accident.

### CODE REVIEW

**Comment by iankronquist** [comment]
It seems to be used in the [provider template]( https://github.com/puppetlabs/puppetlabs-strings/blob/master/lib/puppet_x/puppetlabs/strings/yard/templates/default/provider/setup.rb#L21).

**Comment by roidelapluie** [comment]
@iankronquist the .erb, not the .rb

**Comment by roidelapluie** [comment]
https://github.com/puppetlabhttps://github.com/puppetlabs/puppetlabs-strings/blob/26a9d73ef2b7b9897f9c61a4d82e0cdd9c32b14c/lib/puppet_x/puppetlabs/strings/yard/templates/default/provider/html/command_details.rbs/puppetlabs-strings/blob/26a9d73ef2b7b9897f9c61a4d82e0cdd9c32b14c/lib/puppet_x/puppetlabs/strings/yard/templates/default/provider/html/command_details.erb

**Comment by iankronquist** [comment]
Ah! Yes, sorry, I didn't notice that. Yeah, this is fine then. @HAIL9000 r?

**Comment by HAIL9000** [comment]
@iankronquist It looks the .erb and .rb files have different content. Is HTML from this .rb actually not needed...?

**Comment by iankronquist** [comment]
@HAIL9000 I think the erb is correct, and the rb is wrong. Oops, sorry.

**Comment by roidelapluie** [comment]
I found this because our CI check does:

```
if [[ -d lib ]]
then
echo
echo Checking RB files
echo

find lib -name '*.rb' -print0 | xargs -0 -L 1 ruby -c
fi
```

**Comment by HAIL9000** [comment]
@iankronquist I think I'm still confused... so we don't need the parameter summary or features? Or are those just covered somewhere else that I'm missing

**Comment by roidelapluie** [comment]
@HAIL9000 https://github.com/puppetlabs/puppetlabs-strings/blob/5206c8c62e91b564ae1de1341c662a21b5740bb2/lib/puppet_x/puppetlabs/strings/yard/templates/default/type/html/parameter_details.erb

**Pull request merged**
